#!/usr/bin/env python3
"""
Enhanced clinical report generation with risk assessment and recommendations.

Transforms raw detections into professional medical reports suitable for clinicians.
"""

from typing import List, Dict
from datetime import datetime
from src.risk_assessment import RiskAssessment, generate_smart_report


def generate_enhanced_clinical_report(detections: List[dict]) -> str:
    """
    Generate professional clinical report with integrated risk assessment.
    
    Args:
        detections: List of detection dicts with 'size_mm', 'confidence', etc.
    
    Returns:
        Formatted clinical report as string
    """
    if not detections:
        return TEMPLATE_NO_NODULES.format(datetime=datetime.now().strftime("%Y-%m-%d"))
    
    # Run risk assessment
    analysis = RiskAssessment.assess_detections(detections)
    
    # Generate smart report
    return generate_smart_report(analysis)


# Fallback template for when there are no nodules
TEMPLATE_NO_NODULES = """
================================================================================
PULMONARY NODULE DETECTION REPORT
Generated: {datetime}
================================================================================

FINDINGS:
--------
No suspicious pulmonary nodules detected on imaging.

IMPRESSION:
-----------
No findings suggestive of malignancy identified.

RECOMMENDATIONS:
----------------
1. Routine follow-up imaging as per institutional protocol
2. Continue annual low-dose CT screening if indicated
3. Smoking cessation if applicable

CLINICAL NOTES:
---------------
This report is based on automated AI analysis combined with radiologist review.
Any discrepancies between automated and manual assessment should be resolved
through clinical correlation.

================================================================================
Report generated by: Lung Nodule Detection AI System
Status: FINAL
================================================================================
""".strip()


def format_report_for_download(report_text: str, scan_info: Dict = None) -> str:
    """
    Format report for PDF/download with header and footer.
    
    Args:
        report_text: Main report content
        scan_info: Optional dict with patient/scan details
    
    Returns:
        Formatted report with header/footer
    """
    header = "=" * 80 + "\n"
    header += "CONFIDENTIAL - MEDICAL REPORT\n"
    header += "=" * 80 + "\n"
    
    if scan_info:
        header += f"Patient: {scan_info.get('patient_name', 'Anonymous')}\n"
        header += f"Study Date: {scan_info.get('study_date', datetime.now().strftime('%Y-%m-%d'))}\n"
        header += f"Modality: {scan_info.get('modality', 'CT Chest')}\n"
        header += "=" * 80 + "\n\n"
    
    footer = "\n" + "=" * 80
    footer += "\nThis report was generated using automated AI analysis.\n"
    footer += "Final interpretation by a qualified radiologist is recommended.\n"
    footer += "=" * 80
    
    return header + report_text + footer


if __name__ == "__main__":
    # Test with sample detections
    sample_detections = [
        {"size_mm": 8.5, "confidence": 0.92, "center_x": 100, "center_y": 150, "center_z": 45},
        {"size_mm": 5.2, "confidence": 0.78, "center_x": 200, "center_y": 180, "center_z": 85},
    ]
    
    report = generate_enhanced_clinical_report(sample_detections)
    print(report)
